### ISSUE TITLE
The Clean Coder, Chapter 1, 2, 3, 2022-03-11

### ISSUE THREAD

**Issue by jongfeel** [virnect-corp/BookClub#3]
### 8 Mar

- Chapter 1,2,3을 읽고 아래와 같이 진행
  - (Required) chapter 당 한 개 이상 논의 내용 작성, 총 3개의 논의 내용 필요 
  - (Optional) 책 내용 정리 외에 추가 논의, 질문, 공유 정보 작성
- Reviewer는 자신을 제외한 멤버 모두 할당

### Until, 11 Mar 12:29

다른 멤버의 pull request review를 3일의 시간에 진행 해야 하며
pull request 당 적어도 1개 이상 코멘트 추가, 이후 approve를 통해 리뷰 했다는 걸 인증

### 11 Mar

- 회사 3-3 회의실에서 점심 + 리뷰 미팅 진행

### Order (Updated asynchronous real time)

앉은 순서대로 clockwise order?

**Comment by jongfeelkim-VIRNECT** [comment]
슬랙 채널에 영권님을 제외하고 모두 하는 것으로 알고
제가 assignee를 걸어 뒀습니다.
