### ISSUE TITLE
함께 자라기 - 2 함께, 2022-10-28

### ISSUE THREAD

**Issue by jongfeel** [virnect-corp/BookClub#99]
##  10월 08일 ~ 10월 20일

2 함께 챕터 까지 읽고 아래와 같이 진행
- (Required) chapter 당 한 개 이상 논의 내용 작성
- (Optional) 책 내용 정리 외에 추가 논의, 질문, 공유 정보 작성
- Reviewer는 자신을 제외한 멤버 모두 할당

## Before meeting

다른 멤버의 pull request review를 1일의 시간에 진행 해야 하며
pull request 당 적어도 1개 이상 코멘트 추가, 이후 approve를 통해 리뷰 했다는 걸 인증

## 10월 21일 금요일

12:30 점심 식사 후 금영 6층 회의실 에서 리뷰 미팅 진행
재택이나 연차 이신 분을 위해 teams video call 사용
발표 순서는 pull request 나중에 올린 순서대로 진행

---

저는 싱가포르에 있을 예정이므로 12시 50분 ~ 1시 사이에 teams 콜 해주세요.
싱가포르 현지 시간으로는... 11시 50분 ~ 12시 사이가 되겠군요.

**Comment by jongfeel** [comment]
저의 장기근속휴가와
용호님의 연차로 인해 
모임 1주일 연기

**Comment by jongfeel** [comment]
10월 25일 점심시간에 진행

**Comment by silqwer** [comment]
주말에 공가 올려서 연차 3개 날린 1인 ㅠㅠ
